blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://community.open-ecosystem.com/c/challenges
    about: Ask questions and discuss challenges in the Open Ecosystem community.

