apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: "${{ values.description }}"
spec:
  type: service
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  system: ${{ values.system }}
