apiVersion: v1
kind: Pod
metadata:
  name: citizen
  namespace: gallia
  labels:
    republic.rome/gens: iulia
    republic.rome/province: gallia
spec:
  containers:
    - name: app
      image: busybox:stable
      command: ["sleep", "infinity"]
      securityContext:
        privileged: false
---
apiVersion: v1
kind: Pod
metadata:
  name: citizen
  namespace: hispania
  labels:
    republic.rome/gens: cornelia
    republic.rome/province: hispania
spec:
  containers:
    - name: app
      image: busybox:stable
      command: ["sleep", "infinity"]
      securityContext:
        privileged: false
---
apiVersion: v1
kind: Pod
metadata:
  name: citizen
  namespace: britannia
  labels:
    republic.rome/gens: claudia
    republic.rome/province: britannia
spec:
  containers:
    - name: app
      image: busybox:stable
      command: ["sleep", "infinity"]
      securityContext:
        privileged: false
---
apiVersion: v1
kind: Pod
metadata:
  name: citizen
  namespace: aegyptus
  labels:
    republic.rome/gens: aemilia
    republic.rome/province: aegyptus
    republic.rome/role: scribe
spec:
  containers:
    - name: app
      image: busybox:stable
      command: ["sleep", "infinity"]
      securityContext:
        privileged: false
