apiVersion: v1
kind: Pod
metadata:
  name: peregrinus
  labels:
    republic.rome/gens: forum-romanum
    republic.rome/traveler: peregrinus
spec:
  restartPolicy: Never
  containers:
    - name: app
      image: busybox:stable
      command: ["sleep", "infinity"]
      securityContext:
        privileged: false
